"""
Reads junction nodes and connectivity edges from the GeoJSON file generated by
export_junction_graph.py, and provides the following features:

  1. load_graph(path)          -> JunctionGraph
     Read the GeoJSON, parse nodes and edges, and build the graph structure.

  2. JunctionGraph.nodes       node list sorted by coordinates (list of NodeInfo)
  3. JunctionGraph.matrix      NxN adjacency matrix (list of list, 0/1)
  4. JunctionGraph.coord(idx)  look up (x, y, z) coordinates by matrix index
  5. JunctionGraph.index(jid)  look up the matrix index by junction_id
  6. JunctionGraph.neighbors(idx) return the list of indices directly connected to idx

Usage example:
  from junction_graph_matrix import load_graph

  g = load_graph("junction_graph.geojson")

  print(g.size)                 # total number of nodes
  print(g.coord(0))             # coordinates of node 0
  print(g.neighbors(0))         # indices of nodes adjacent to node 0
  print(g.matrix[0][1])         # whether node 0 and node 1 are connected (0 or 1)

  # Iterate over all nodes
  for node in g.nodes:
      print(node.idx, node.junction_id, node.x, node.y, node.z)

  # Print the full matrix (for small graphs)
  g.print_matrix()
"""

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple


@dataclass
class NodeInfo:
    idx: int
    junction_id: int
    x: float
    y: float
    z: float

    @property
    def coords(self) -> Tuple[float, float, float]:
        return (self.x, self.y, self.z)

    def __repr__(self) -> str:
        return (
            f"NodeInfo(idx={self.idx}, jid={self.junction_id}, "
            f"x={self.x:.2f}, y={self.y:.2f}, z={self.z:.2f})"
        )


@dataclass
class JunctionGraph:
    nodes: List[NodeInfo]
    matrix: List[List[int]]
    _jid_to_idx: Dict[int, int] = field(default_factory=dict, repr=False)

    @property
    def size(self) -> int:
        return len(self.nodes)

    def coord(self, idx: int) -> Tuple[float, float, float]:
        if idx < 0 or idx >= self.size:
            raise IndexError(f"idx={idx} out of range [0, {self.size - 1}]")
        n = self.nodes[idx]
        return (n.x, n.y, n.z)

    def index(self, junction_id: int) -> int:
        if junction_id not in self._jid_to_idx:
            raise KeyError(f"junction_id={junction_id} is not in the graph")
        return self._jid_to_idx[junction_id]

    def neighbors(self, idx: int) -> List[int]:
        if idx < 0 or idx >= self.size:
            raise IndexError(f"idx={idx} out of range [0, {self.size - 1}]")
        return [j for j, val in enumerate(self.matrix[idx]) if val == 1]

    def are_connected(self, idx_a: int, idx_b: int) -> bool:
        return self.matrix[idx_a][idx_b] == 1

    def print_matrix(self, max_size: int = 30) -> None:
        n = self.size
        if n > max_size:
            return
        header = "     " + "  ".join(f"{j:2d}" for j in range(n))
        print(header)
        print("     " + "----" * n)
        for i, row in enumerate(self.matrix):
            vals = "  ".join(str(v) for v in row)
            print(f"{i:3d} | {vals}")

    def summary(self) -> str:
        edge_count = sum(
            self.matrix[i][j]
            for i in range(self.size)
            for j in range(i + 1, self.size)
        )
        return (
            f"JunctionGraph: {self.size} nodes, {edge_count} undirected edges"
        )

    def __repr__(self) -> str:
        return self.summary()


def load_graph(geojson_path: str) -> JunctionGraph:
    path = Path(geojson_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {geojson_path}")

    with path.open(encoding="utf-8") as f:
        gj = json.load(f)

    features = gj.get("features", [])

    raw_nodes: List[Tuple[int, float, float, float]] = []  # (jid, x, y, z)
    for feat in features:
        if (feat.get("geometry") or {}).get("type") != "Point":
            continue
        props = feat.get("properties") or {}
        jid = props.get("junction_id")
        coords = feat["geometry"]["coordinates"]
        if jid is None or len(coords) < 2:
            continue
        x, y = float(coords[0]), float(coords[1])
        z = float(coords[2]) if len(coords) >= 3 else 0.0
        raw_nodes.append((int(jid), x, y, z))

    if not raw_nodes:
        raise ValueError("No Point nodes found in the GeoJSON; please check the file format.")

    raw_nodes.sort(key=lambda t: (t[2], t[1]))  # (y, x)

    nodes: List[NodeInfo] = []
    jid_to_idx: Dict[int, int] = {}
    for idx, (jid, x, y, z) in enumerate(raw_nodes):
        nodes.append(NodeInfo(idx=idx, junction_id=jid, x=x, y=y, z=z))
        jid_to_idx[jid] = idx

    n = len(nodes)

    matrix: List[List[int]] = [[0] * n for _ in range(n)]
    edge_count = 0
    skipped = 0
    for feat in features:
        if (feat.get("geometry") or {}).get("type") != "LineString":
            continue
        props = feat.get("properties") or {}
        jid_a = props.get("from_junction")
        jid_b = props.get("to_junction")
        if jid_a is None or jid_b is None:
            skipped += 1
            continue
        jid_a, jid_b = int(jid_a), int(jid_b)
        if jid_a not in jid_to_idx or jid_b not in jid_to_idx:
            skipped += 1
            continue
        i, j = jid_to_idx[jid_a], jid_to_idx[jid_b]
        if matrix[i][j] == 0:
            matrix[i][j] = 1
            matrix[j][i] = 1
            edge_count += 1

    if skipped:
        print(f"[WARN] Skipped {skipped} edge(s) (node not in graph or missing properties)")

    print(
        f"[OK] Graph built: {n} nodes, {edge_count} undirected edges"
        f" (from {path.name})"
    )

    return JunctionGraph(
        nodes=nodes,
        matrix=matrix,
        _jid_to_idx=jid_to_idx,
    )



def _main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description="Build the junction adjacency matrix from a GeoJSON file and print a summary."
    )
    parser.add_argument("geojson", help="Path to the input GeoJSON file")
    parser.add_argument(
        "--print-matrix", action="store_true",
        help="Print the full adjacency matrix (effective when node count <= 30)"
    )
    parser.add_argument(
        "--query", type=int, default=None, metavar="IDX",
        help="Query the coordinates and neighbors of the node with the given index"
    )
    args = parser.parse_args()

    g = load_graph(args.geojson)
    print(g.summary())

    if args.print_matrix:
        g.print_matrix()

    if args.query is not None:
        idx = args.query
        x, y, z = g.coord(idx)
        print(f"\nNode {idx}: junction_id={g.nodes[idx].junction_id}  "
              f"x={x:.3f}  y={y:.3f}  z={z:.3f}")
        nb = g.neighbors(idx)
        print(f"  Neighbor indices: {nb}")
        for nidx in nb:
            nx, ny, nz = g.coord(nidx)
            print(f"    [{nidx}] jid={g.nodes[nidx].junction_id}  "
                  f"({nx:.2f}, {ny:.2f}, {nz:.2f})")

    print("\nAll nodes (idx | junction_id | x | y | z):")
    for node in g.nodes:
        print(f"  {node.idx:4d} | {node.junction_id:6d} | "
              f"{node.x:10.3f} | {node.y:10.3f} | {node.z:7.3f}")


if __name__ == "__main__":
    _main()
